# Generated by Django 4.1.4 on 2022-12-19 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hall', to='ticket.hall'),
        ),
    ]
