# Generated by Django 3.2.4 on 2021-06-04 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_movie_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest', to='ticket.movie'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie', to='ticket.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='end_date',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hall', to='ticket.hall'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='start_date',
            field=models.TimeField(),
        ),
    ]
