# Generated by Django 4.1.4 on 2022-12-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_remove_hall_movie_movie_hall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='hall',
        ),
    ]
