# Generated by Django 4.1.4 on 2022-12-19 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_remove_reservation_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='GuestReservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Guest', to='ticket.reservation'),
        ),
    ]
