# Generated by Django 3.2.4 on 2021-06-05 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_remove_movie_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Guest', to='ticket.movie'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Hall', to='ticket.movie'),
        ),
    ]
