# Generated by Django 4.1.4 on 2022-12-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_guest_guestreservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='GuestReservation',
        ),
    ]
